const LEGACY_WRONG_QUESTIONS = [
  {
    id: 'LEGACY-1-03',
    set: 'legacy-1',
    chapter: '1장 테스트 기초',
    lo: '1.3.1',
    level: 'K2',
    text: '명세에 정의된 기능은 모두 구현했지만 사용자가 원하는 상품을 찾기 어려워 시스템을 사용하지 않는 상황과 관련된 테스팅 원리는 무엇인가?',
    options: ['테스트는 정황에 의존한다', '결함 집중', '테스트 마모', '오류 부재의 궤변에 주의해야 한다'],
    answer: [3],
    explanation: '시스템이 명세를 만족하고 알려진 결함이 거의 없더라도 사용자의 실제 요구와 기대를 충족하지 못하면 성공한 제품이 아니다. 이것이 오류 부재의 궤변이다.',
    reviewLabel: '1회 3번'
  },
  {
    id: 'LEGACY-1-10',
    set: 'legacy-1',
    chapter: '2장 SDLC 전반의 테스팅',
    lo: '2.1.3',
    level: 'K1',
    text: '원하는 시스템 행동을 비즈니스가 읽을 수 있는 형식으로 표현하며 흔히 Given–When–Then 구조를 사용하는 접근법은 무엇인가?',
    options: ['TDD', 'BDD', 'ATDD', 'DevOps'],
    answer: [1],
    explanation: 'BDD는 원하는 행동을 비즈니스 친화적인 시나리오로 표현하며 Given–When–Then 형식을 흔히 사용한다. ATDD는 이해관계자가 협업하여 구현 전에 인수 조건과 인수 테스트를 정의하는 데 중심을 둔다.',
    reviewLabel: '1회 10번'
  },
  {
    id: 'LEGACY-1-18',
    set: 'legacy-1',
    chapter: '4장 테스트 분석 및 설계',
    lo: '4.2.2',
    level: 'K3',
    text: '유효 입력 범위가 1~100일 때 3값 경계값 분석에 필요한 값의 집합은?',
    options: ['1, 100', '0, 1, 100, 101', '0, 1, 2, 99, 100, 101', '-1, 0, 1, 100, 101, 102'],
    answer: [2],
    explanation: '3값 경계값 분석은 각 경계의 바로 아래, 경계 자체, 바로 위 값을 선택한다. 하한 1에서는 0·1·2, 상한 100에서는 99·100·101을 선택한다.',
    reviewLabel: '1회 18번'
  },
  {
    id: 'LEGACY-1-25',
    set: 'legacy-1',
    chapter: '4장 테스트 분석 및 설계',
    lo: '4.5.1',
    level: 'K2',
    text: '사용자 스토리의 3C를 올바르게 나열한 것은?',
    options: ['Card, Communication, Criteria', 'Card, Conversation, Confirmation', 'Case, Conversation, Completion', 'Customer, Component, Criteria'],
    answer: [1],
    explanation: '사용자 스토리는 카드에 간결하게 기록하고(Card), 이해관계자 간 대화로 구체화하며(Conversation), 인수 조건으로 구현 결과를 확인한다(Confirmation).',
    reviewLabel: '1회 25번'
  },
  {
    id: 'LEGACY-1-35',
    set: 'legacy-1',
    chapter: '5장 테스트 활동 관리',
    lo: '5.2.1',
    level: 'K2',
    text: '다음 중 제품 리스크에 해당하는 것은?',
    options: ['핵심 테스터가 퇴사할 가능성', '테스트 환경 구축이 지연될 가능성', '결제 금액 계산 오류로 고객에게 잘못된 금액이 청구될 가능성', '테스트 예산이 삭감될 가능성'],
    answer: [2],
    explanation: '결제 계산 오류는 제품 자체의 기능과 품질이 실패하는 제품 리스크다. 인력·환경·예산 문제는 프로젝트 수행에 영향을 주는 프로젝트 리스크다.',
    reviewLabel: '1회 35번'
  },
  {
    id: 'LEGACY-1-37',
    set: 'legacy-1',
    chapter: '5장 테스트 활동 관리',
    lo: '5.1.7',
    level: 'K2',
    text: '애자일 테스팅 사분면의 관점과 목적, 테스트 유형을 올바르게 연결한 것은?',
    options: ['Q1 — 비즈니스 관점에서 팀을 지원하는 사용성 테스팅', 'Q2 — 기술 관점에서 제품을 비평하는 성능 테스팅', 'Q3 — 비즈니스 관점에서 제품을 비평하는 탐색적·사용성 테스팅', 'Q4 — 비즈니스 관점에서 팀을 지원하는 인수 테스팅'],
    answer: [2],
    explanation: 'Q2는 비즈니스 관점에서 팀을 지원하는 기능 예제 중심이다. Q3은 비즈니스 관점에서 제품을 비평하며 탐색적·사용성·사용자 인수 테스팅을 포함한다. 성능·보안 테스팅은 기술 관점에서 제품을 비평하는 Q4에 속한다.',
    reviewLabel: '1회 37번'
  },
  {
    id: 'LEGACY-2-05',
    set: 'legacy-2',
    chapter: '1장 테스트 기초',
    lo: '1.4.1',
    level: 'K2',
    text: '테스트 분석 활동의 주요 산출물로 가장 적절한 것은?',
    options: ['테스트 완료 보고서', '자동화 실행 로그', '우선순위가 지정된 테스트 컨디션', '수정된 소스 코드'],
    answer: [2],
    explanation: '테스트 분석은 테스트 베이시스를 검토하여 무엇을 테스트할지 식별하고 테스트 컨디션을 정의·우선순위화한다.',
    reviewLabel: '2회 5번'
  },
  {
    id: 'LEGACY-2-11',
    set: 'legacy-2',
    chapter: '2장 SDLC 전반의 테스팅',
    lo: '2.1.3',
    level: 'K2',
    text: '테스트 주도 개발(TDD)의 기본 반복 순서로 옳은 것은?',
    options: ['코드 작성 → 배포 → 테스트 삭제', '실패하는 테스트 작성 → 최소 코드 작성 → 리팩터링', '요구사항 승인 → 운영 배포 → 회귀 테스트', '테스트 계획 → 인수 테스트 → 요구사항 작성'],
    answer: [1],
    explanation: 'TDD는 작은 단위의 실패하는 테스트를 먼저 작성하고 이를 통과하는 최소 코드를 구현한 뒤 리팩터링하는 주기를 반복한다.',
    reviewLabel: '2회 11번'
  },
  {
    id: 'LEGACY-2-18',
    set: 'legacy-2',
    chapter: '3장 정적 테스팅',
    lo: '3.2.3',
    level: 'K2',
    text: '일반적으로 가장 형식적이며 정의된 역할, 메트릭과 종료 기준을 사용하는 리뷰 유형은?',
    options: ['비공식 리뷰', '워크스루', '기술 리뷰', '인스펙션'],
    answer: [3],
    explanation: '인스펙션은 가장 형식적인 리뷰 유형으로 정의된 프로세스, 역할, 데이터 수집과 종료 기준을 사용한다.',
    reviewLabel: '2회 18번'
  },
  {
    id: 'LEGACY-2-23',
    set: 'legacy-2',
    chapter: '4장 테스트 분석 및 설계',
    lo: '4.3.1',
    level: 'K3',
    text: '다음 의사코드를 x=1로 한 번 실행했다. 구문 커버리지는? “if x > 0 then y = 1; print(y)”',
    options: ['100%', '75%', '50%', '25%'],
    answer: [0],
    explanation: 'x=1이면 y=1 대입과 print 구문이 모두 실행되므로 실행 가능한 구문 커버리지는 100%다.',
    reviewLabel: '2회 23번'
  },
  {
    id: 'LEGACY-2-24',
    set: 'legacy-2',
    chapter: '4장 테스트 분석 및 설계',
    lo: '4.3.2',
    level: 'K3',
    text: '직전 문제의 의사코드를 x=1로만 실행했을 때 분기 커버리지는?',
    options: ['100%', '75%', '50%', '25%'],
    answer: [2],
    explanation: '결정 결과 참과 거짓 중 참만 실행했으므로 분기 커버리지는 1/2, 즉 50%다.',
    reviewLabel: '2회 24번'
  },
  {
    id: 'LEGACY-2-32',
    set: 'legacy-2',
    chapter: '5장 테스트 활동 관리',
    lo: '5.2.1',
    level: 'K2',
    text: '다음 중 제품 리스크에 해당하는 것은?',
    options: ['핵심 테스터의 퇴사 가능성', '테스트 환경 구축 지연', '결제 계산 오류로 고객에게 잘못 청구될 가능성', '테스트 예산 삭감'],
    answer: [2],
    explanation: '제품 리스크는 제품의 품질 특성과 관련된다. 인력, 일정, 환경과 예산 문제는 프로젝트 리스크다.',
    reviewLabel: '2회 32번'
  },
  {
    id: 'LEGACY-2-33',
    set: 'legacy-2',
    chapter: '5장 테스트 활동 관리',
    lo: '5.2.2',
    level: 'K2',
    text: '일반적으로 제품 리스크 수준을 결정하는 두 요소는?',
    options: ['발생 가능성과 영향도', '테스터 수와 개발자 수', '코드 줄 수와 테스트 수', '일정과 회의 횟수'],
    answer: [0],
    explanation: '리스크 수준은 보통 부정적 사건의 발생 가능성과 발생했을 때의 영향도를 조합해 평가한다.',
    reviewLabel: '2회 33번'
  }
];
